let inputWidth;
let inputHeight;
inputWidth = prompt("Nhập vào chiều dài");
document.write("The Width is : " + inputWidth);
document.write('<br>');
inputHeight = prompt("Nhập vào chiều rộng");
document.write("The Height is : " + inputHeight);
document.write('<br>');
let Width = parseInt(inputWidth);
let Height = parseInt(inputHeight);
let aria = inputWidth * inputHeight;
document.write("The aria is : " + aria);